# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNDemo' do
 	
    pod 'MOBFoundation'
    pod 'ShareSDK3/ShareSDKUI'
    pod 'ShareSDK3/ShareSDKPlatforms/QQ'
    
    pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
    pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
    pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
    pod 'pop'
    pod 'SDWebImage'
    pod 'Masonry'
    
    #  pod 'AMap3DMap'
    pod 'AMapSearch'
    pod 'AMapLocation'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

end
